# Generated by Django 5.2.4 on 2025-07-20 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('autor_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('nacionalidad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('noticia_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=80)),
                ('subtitulo', models.CharField(max_length=150)),
                ('contenido', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('imagen', models.ImageField(upload_to='')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.autor')),
                ('categoria', models.ManyToManyField(to='noticias.categoria')),
            ],
        ),
    ]
